url: http://apextom.com

pygments: true
permalink: pretty
markdown: redcarpet

redcarpet:
  extensions: [no_intra_emphasis, fenced_code_blocks, strikethrough, space_after_header, superscript, tables, with_toc_data]

title: Apex - Tom 工作室
description: Apex - Tom 工作室官方网站

language: zh-CN
author:
  name: Apex - Tom Workshop
  url: http://apextom.com
